title: Furman Now! Documentation
description: The basic development documentation for the Furman Now! mobile app, built on Expo for React Native.
theme: just-the-docs

url: https://mpeeler.github.io/FurmanNowDocs

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: /assets/docs-logo.png
favicon: /assets/icon.png
color_scheme: dark
